export const countryNameMap: { [key: string]: string } = {
  // Europa
  'España': 'Spain',
  'Francia': 'France',
  'Italia': 'Italy',
  'Alemania': 'Germany',
  'Reino Unido': 'United Kingdom',
  'Portugal': 'Portugal',
  'Suiza': 'Switzerland',
  'Bélgica': 'Belgium',
  'Países Bajos': 'Netherlands',
  'Dinamarca': 'Denmark',
  'Suecia': 'Sweden',
  'Noruega': 'Norway',
  'Finlandia': 'Finland',
  'Rusia': 'Russia',
  'Ucrania': 'Ukraine',
  'Polonia': 'Poland',
  'Austria': 'Austria',
  'República Checa': 'Czech Republic',
  'Eslovaquia': 'Slovakia',
  'Hungría': 'Hungary',
  'Rumanía': 'Romania',
  'Bulgaria': 'Bulgaria',
  'Belarús': 'Belarus',
  'Grecia': 'Greece',
  'Turquía': 'Turkey',
  'Croacia': 'Croatia',
  'Eslovenia': 'Slovenia',
  'Bosnia y Herzegovina': 'Bosnia and Herzegovina',
  'Serbia': 'Serbia',
  'Montenegro': 'Montenegro',
  'Macedonia del Norte': 'North Macedonia',
  'Albania': 'Albania',
  'Estonia': 'Estonia',
  'Letonia': 'Latvia',
  'Lituania': 'Lithuania',
  'Bielorrusia': 'Belarus',
  'Moldavia': 'Moldova',
  'Irlanda': 'Ireland',
  'Islandia': 'Iceland',
  'Malta': 'Malta',
  'Chipre': 'Cyprus',
  'Luxemburgo': 'Luxembourg',
  'Liechtenstein': 'Liechtenstein',
  'Andorra': 'Andorra',
  'Mónaco': 'Monaco',
  'San Marino': 'San Marino',
  'Ciudad del Vaticano': 'Vatican City',

  // América del Norte
  'Estados Unidos de América': 'United States of America',
  'Canadá': 'Canada',
  'México': 'Mexico',
  'Groenlandia': 'Greenland',
  'Bermudas': 'Bermuda',
  'San Pedro y Miquelón': 'Saint Pierre and Miquelon',

  // América Central
  'Belice': 'Belize',
  'Guatemala': 'Guatemala',
  'El Salvador': 'El Salvador',
  'Honduras': 'Honduras',
  'Nicaragua': 'Nicaragua',
  'Costa Rica': 'Costa Rica',
  'Panamá': 'Panama',
  'Cuba': 'Cuba',
  'Jamaica': 'Jamaica',
  'Haití': 'Haiti',
  'República Dominicana': 'Dominican Republic',
  'Puerto Rico': 'Puerto Rico',
  'Bahamas': 'Bahamas',
  'Antigua y Barbuda': 'Antigua and Barbuda',
  'Barbados': 'Barbados',
  'Dominica': 'Dominica',
  'Granada': 'Grenada',
  'San Cristóbal y Nieves': 'Saint Kitts and Nevis',
  'Santa Lucía': 'Saint Lucia',
  'San Vicente y las Granadinas': 'Saint Vincent and the Grenadines',
  'Trinidad y Tobago': 'Trinidad and Tobago',

  // América del Sur
  'Brasil': 'Brazil',
  'Argentina': 'Argentina',
  'Chile': 'Chile',
  'Colombia': 'Colombia',
  'Perú': 'Peru',
  'Venezuela': 'Venezuela',
  'Ecuador': 'Ecuador',
  'Bolivia': 'Bolivia',
  'Paraguay': 'Paraguay',
  'Uruguay': 'Uruguay',
  'Guyana': 'Guyana',
  'Surinam': 'Suriname',
  'Guayana Francesa': 'French Guiana',
  'Islas Malvinas': 'Falkland Islands',

  // Asia
  'China': 'China',
  'Japón': 'Japan',
  'Corea del Sur': 'South Korea',
  'Corea del Norte': 'North Korea',
  'India': 'India',
  'Pakistán': 'Pakistan',
  'Bangladés': 'Bangladesh',
  'Nepal': 'Nepal',
  'Bután': 'Bhutan',
  'Sri Lanka': 'Sri Lanka',
  'Maldivas': 'Maldives',
  'Afganistán': 'Afghanistan',
  'Irán': 'Iran',
  'Irak': 'Iraq',
  'Siria': 'Syria',
  'Líbano': 'Lebanon',
  'Israel': 'Israel',
  'Palestina': 'Palestine',
  'Jordania': 'Jordan',
  'Arabia Saudita': 'Saudi Arabia',
  'Yemen': 'Yemen',
  'Omán': 'Oman',
  'Emiratos Árabes Unidos': 'United Arab Emirates',
  'Qatar': 'Qatar',
  'Baréin': 'Bahrain',
  'Kuwait': 'Kuwait',
  'Kazajistán': 'Kazakhstan',
  'Uzbekistán': 'Uzbekistan',
  'Azerbaiyán': 'Azerbaijan',
  'Turkmenistán': 'Turkmenistan',
  'Kirguistán': 'Kyrgyzstan',
  'Tayikistán': 'Tajikistan',
  'Mongolia': 'Mongolia',
  'Vietnam': 'Vietnam',
  'Laos': 'Laos',
  'Camboya': 'Cambodia',
  'Tailandia': 'Thailand',
  'Myanmar': 'Myanmar',
  'Malasia': 'Malaysia',
  'Singapur': 'Singapore',
  'Indonesia': 'Indonesia',
  'Filipinas': 'Philippines',
  'Brunei': 'Brunei',
  'Timor Oriental': 'East Timor',
  'Taiwán': 'Taiwan',
  'Hong Kong': 'Hong Kong',
  'Macao': 'Macau',

  // Oceanía
  'Australia': 'Australia',
  'Nueva Zelanda': 'New Zealand',
  'Papúa Nueva Guinea': 'Papua New Guinea',
  'Fiyi': 'Fiji',
  'Islas Salomón': 'Solomon Islands',
  'Vanuatu': 'Vanuatu',
  'Samoa': 'Samoa',
  'Tonga': 'Tonga',
  'Kiribati': 'Kiribati',
  'Tuvalu': 'Tuvalu',
  'Nauru': 'Nauru',
  'Palaos': 'Palau',
  'Micronesia': 'Micronesia',
  'Islas Marshall': 'Marshall Islands',

  // África
  'Egipto': 'Egypt',
  'Libia': 'Libya',
  'Túnez': 'Tunisia',
  'Argelia': 'Algeria',
  'Marruecos': 'Morocco',
  'Sahara Occidental': 'Western Sahara',
  'Mauritania': 'Mauritania',
  'Malí': 'Mali',
  'Níger': 'Niger',
  'Chad': 'Chad',
  'Sudán': 'Sudan',
  'Sudán del Sur': 'South Sudan',
  'Eritrea': 'Eritrea',
  'Yibuti': 'Djibouti',
  'Somalia': 'Somalia',
  'Somalilandia': 'Somaliland',
  'Etiopía': 'Ethiopia',
  'Kenia': 'Kenya',
  'Uganda': 'Uganda',
  'Tanzania': 'Tanzania',
  'Ruanda': 'Rwanda',
  'Burundi': 'Burundi',
  'República Democrática del Congo': 'Democratic Republic of the Congo',
  'República del Congo': 'Republic of the Congo',
  'Gabón': 'Gabon',
  'Guinea Ecuatorial': 'Equatorial Guinea',
  'Santo Tomé y Príncipe': 'Sao Tome and Principe',
  'Camerún': 'Cameroon',
  'República Centroafricana': 'Central African Republic',
  'Nigeria': 'Nigeria',
  'Benín': 'Benin',
  'Togo': 'Togo',
  'Ghana': 'Ghana',
  'Costa de Marfil': 'Ivory Coast',
  'Liberia': 'Liberia',
  'Sierra Leona': 'Sierra Leone',
  'Guinea': 'Guinea',
  'Guinea-Bisáu': 'Guinea-Bissau',
  'Senegal': 'Senegal',
  'Gambia': 'Gambia',
  'Burkina Faso': 'Burkina Faso',
  'Malaui': 'Malawi',
  'Zambia': 'Zambia',
  'Zimbabue': 'Zimbabwe',
  'Botsuana': 'Botswana',
  'Namibia': 'Namibia',
  'Angola': 'Angola',
  'Mozambique': 'Mozambique',
  'Madagascar': 'Madagascar',
  'Comoras': 'Comoros',
  'Seychelles': 'Seychelles',
  'Mauricio': 'Mauritius',
  'Cabo Verde': 'Cape Verde',
  'Suazilandia': 'Eswatini',
  'Lesoto': 'Lesotho',
  'Sudáfrica': 'South Africa'
}; 